personal_portfolio/Blog/urls.py
from django.urls import path
from . import views
app_name = 'blog'
urlpatterns = [
 
    path('', views.all_blogs,name='all_blogs' ),
    path('<int:blog_id>/', views.detail,name='detail' ),
    

]

personal_portfolio/personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from Portfolio import views
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home,name='home' ),
    path('blog/',include('Blog.urls')),
    path('ml_project', views.ml_project,name='ml_project' )
    

]
urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

personal_portfolio/Blog/models.py
from django.db import models

# Create your models here.
class Blog(models.Model):
    title=models.CharField(max_length=100)
    description=models.CharField(max_length=1000)
    date=models.DateField()
    def __str__(self):
        return self.title

personal_portfolio/Portfolio/models.py
from django.db import models

# Create your models here.
class Project(models.Model):
    title=models.CharField(max_length=100)
    description=models.CharField(max_length=250)
    image=models.ImageField(upload_to='Portfolio/images/')
    url=models.URLField(blank=True)
    def __str__(self):
        return self.title

personal_portfolio/Portfolio/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(label="Name", max_length=100)
    email = forms.EmailField(label="Email")
    message = forms.CharField(label="Message", widget=forms.Textarea)

personal_portfolio/Blog/views.py
from django.shortcuts import render,get_object_or_404
from .models import Blog
# Create your views here.

def all_blogs(request):
    blogs=Blog.objects.order_by('-date')
    return render(request,'blogs/all_blogs.html',{'blogs':blogs})
def detail(request,blog_id):
    blog=get_object_or_404(Blog,pk=blog_id)
    return render(request,'blogs/details.html',{'blog':blog})

personal_portfolio/Portfolio/views.py
from django.shortcuts import render, redirect
from .models import Project
from django.core.mail import send_mail
from .forms import ContactForm
from django.contrib import messages

def home(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            message = form.cleaned_data['message']
            
            send_mail(
                subject=f"New Message from {name}",
                message=message,
                from_email='santhoshmanoharan.edu@gmail.com',
                recipient_list=[email],  # Replace with your email address
                fail_silently=False,
            )
            messages.success(request, 'Email sent successfully!')
            # return redirect('home')  # Redirect to home page to display the message
    else:
        form = ContactForm()

    projects = Project.objects.all()
    return render(request, 'portfolio/home.html', {'projects': projects, 'form': form})

def ml_project(request):
    return (render(request,'portfolio/ml_project.html'))

personal_portfolio/Blog/templates/blogs/all_blogs.html
{%extends 'portfolio/base.html'%}
{% load static %}
{%block content%}

<h1 id="blogtitle" class="font-weight-bold text-center" >Blog</h1>
<h3 class="text-center mb-5">SAN has written {{blogs.count}} blog{{blogs.count|pluralize}}</h3>

{% for blog in blogs %}
<div class="row justify-content-center my-3">
   <div class="col-md-10">
   <a href="{% url 'blog:detail' blog.id %}">
       <h2>{{blog.title}}</h2>
   </a>
<h5>{{blog.date|date:'M d Y'|upper}}</h5>
<h4>{{blog.description|striptags|truncatechars:100}}</h4>
</div>
</div>
{%endfor%}

{%endblock%}

personal_portfolio/Blog/templates/blogs/details.html
{%extends 'portfolio/base.html'%}
{%load static%}
{%block content%}
<h1 class="text-center mt-5" id="blogdetailtitle">{{blog.title}}</h1>
<h5 class="text-center text-muted mb-5">{{blog.date|date:'F jS Y'}}</h5>
<div id="textdetail"  >
{{ blog.description|safe }}
</div>
{%endblock%}

personal_portfolio/Portfolio/templates/portfolio/base.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css"
      rel="stylesheet"
    />

    <!-- Bootstrap   CSS -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css"
    />
    <link rel="icon" href="{%static 'portfolio/logo.png'%}" />
    <link
      href="https://fonts.googleapis.com/css?family=Bellota+Text&display=swap"
      rel="stylesheet"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Lato&display=swap"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <script
      src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
      integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
      integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
      crossorigin="anonymous"
    ></script>
    <script>
      document.addEventListener("DOMContentLoaded", function () {
        document.querySelectorAll(".side-heading").forEach(function (link) {
          link.addEventListener("click", function (e) {
            e.preventDefault();

            var targetId = this.getAttribute("href").substring(1);
            var targetSection = document.getElementById(targetId);

            if (targetSection) {
              window.scrollTo({
                top: targetSection.offsetTop + 100, // Adjust as needed
                behavior: "smooth",
              });

              // Mark the clicked link as active
              document
                .querySelectorAll(".side-heading")
                .forEach(function (otherLink) {
                  otherLink.classList.remove("active");
                });
              this.classList.add("active");
            }
          });
        });
      });
    </script>
    <link rel="stylesheet" href="{% static 'portfolio/custom.css' %}" />
    <title>S A N</title>
    <!-- ml_project header-->

    <style>
      body {
        margin: 0;
      }
      nav {
        position: fixed;
        top: 50%; /* Adjust as needed */
        right: 20px;

        display: flex;
        flex-direction: column;
        gap: 15px;
        z-index: 2;
      }

      #side-heading {
        color: #343a40;
        text-decoration: none;
        font-weight: normal;
        padding: 15px;
        background-color: #f8f9fa;
        border-radius: 15px;
        cursor: pointer;
        transition: background-color 0.3s ease, color 0.3s ease,
          transform 0.3s ease;
      }

      #side-heading:hover {
        background-color: #343a40;
        color: #fff;
        transform: scale(1.05);
      }

      #side-heading.active {
        font-weight: bold;
      }

      .text-center {
        text-align: center;
      }

      .summary {
        display: inline-block; /* Ensure the summary stays inline */
      }

      .button-box {
        display: inline-block;
        padding: 10px 20px;
        margin: 5px;
        background-color: #007bff;
        border: none;
        color: white;
        text-align: center;
        text-decoration: none;
        font-size: 16px;
        border-radius: 5px;
        cursor: pointer;
        transition: background-color 0.3s;
      }

      .button-box:hover {
        background-color: #0056b3;
      }
    </style>

    <!-- ml_project ends-->

    <!--dispeersion -->
    <style>
      .custom-image {
        height: 350px;
        width: 650px;
        object-fit: cover; /* Optional: Maintain aspect ratio and cover the specified dimensions */
      }
    </style>

    <!--dispersion-->

    <style>
      .cursor {
        display: inline-block;
        width: 0.2em;
        height: 1.2em;
        background-color: black;
        animation: blink 1s infinite;
      }

      @keyframes blink {
        0%,
        100% {
          opacity: 1;
        }
        50% {
          opacity: 0;
        }
      }

      .cursor {
        display: inline-block;
        width: 1em; /* Change the width to control the length of the cursor line */
        height: 0.1em; /* Change the height to control the thickness of the cursor line */
        background-color: black;
        animation: blink 1s infinite;
      }

      body {
        font-family: "Bellota Text", sans-serif; /* Use Bellota Text font for body text */
      }

      h1,
      h2,
      h3,
      h4,
      h5,
      h6 {
        font-family: "Lato", sans-serif; /* Use Lato font for headings */
      }
    </style>
  </head>

  <body>
    <nav
      id="topNav"
      class="navbar navbar-expand-lg navbar-light bg-light"
      style="position: fixed; top: 0; left: 0; width: 100%; z-index: 1000"
    >
      <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">
          <img
            src="{% static 'portfolio/logo.png' %}"
            width="30"
            height="30"
            class="d-inline-block align-top"
            alt="SAN's Logo"
          />
          <span>S A N</span>
        </a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a
                class="nav-link"
                href="{%static 'portfolio/santhoshresume.pdf' %}"
                target="_blank"
                >Resume</a
              >
            </li>

            <li class="nav-item">
              <a
                role="button"
                href="{% url 'blog:all_blogs' %}"
                class="btn btn-primary"
                >Blog</a
              >
            </li>
          </ul>
        </div>
      </div>
    </nav>

    {%block content%}{%endblock%}
  </body>
</html>

personal_portfolio/Portfolio/templates/portfolio/contact_form.html
{%extends 'portfolio/home.html'%}

{%block content%}

  <!-- Contact Form -->
  <div id="contact-form">
    <h2>Contact Me</h2>
    <form method="post" id="contact-form">
        {% csrf_token %}
        <label for="name">Name:</label>
        <input type="text" id="name" name="name" required><br><br>
        <label for="email">Email:</label>
        <input type="email" id="email" name="email" required><br><br>
        <label for="message">Message:</label><br>
        <textarea id="message" name="message" rows="4" required></textarea><br><br>
        <button type="submit">Send Message</button>
    </form>
</div>



{% if messages %}
{% for message in messages %}
    {% if message.tags == 'success' %}
        <div class="alert alert-success">
            {{ message }}
        </div>
    {% endif %}
{% endfor %}
{% endif %}

{%endblock%}

personal_portfolio/Portfolio/templates/portfolio/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css"
      rel="stylesheet"
    />

    <link rel="icon" href="/static/portfolio/logo.png" />
    <link
      href="https://fonts.googleapis.com/css?family=Bellota+Text&display=swap"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Lato&display=swap"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <script
      src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
      integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
      integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
      crossorigin="anonymous"
    ></script>
    <link rel="stylesheet" href="/static/portfolio/custom.css" />
    <style>
      body {
        font-family: "Lato", sans-serif;
        margin: 0;
        padding: 0;
        box-sizing: border-box;
        background-color: #f8f9fa;
        color: #343a40;
        overflow-x: hidden;
      }

      header {
        background-color: #343a40;
        color: white;
        text-align: center;
        padding: 80px 20px;
        margin-bottom: 30px;
        background-attachment: fixed;
        background-position: center;
        background-repeat: no-repeat;
        background-size: cover;
        position: relative;
        box-shadow: 0 5px 15px rgba(0, 0, 0, 0.2);
      }

      header::before {
        content: "";
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background: linear-gradient(
          to bottom,
          rgba(0, 0, 0, 0.5),
          rgba(0, 0, 0, 0)
        );
        z-index: -1;
      }

      nav {
        position: fixed;
        right: 20px;
        top: 50%;
        transform: translateY(-50%);
        display: flex;
        flex-direction: column;
        gap: 15px;
        z-index: 2;
      }

      nav a {
        color: #343a40;
        text-decoration: none;
        font-weight: bold;
        padding: 15px;
        background-color: #f8f9fa;
        border-radius: 15px;
        transition: background-color 0.3s ease, color 0.3s ease,
          transform 0.3s ease;
        cursor: pointer;
      }

      nav a:hover {
        background-color: #343a40;
        color: #fff;
        transform: scale(1.05);
      }

      section {
        padding: 40px;
        text-align: justify;
        background-color: #fff;
        margin: 20px;
        border-radius: 15px;
        box-shadow: 0 10px 20px rgba(0, 0, 0, 0.1);
        position: relative;
        z-index: 1;
        color: #495057;
        opacity: 0;
        transform: translateY(20px);
        transition: opacity 0.6s ease, transform 0.6s ease;
      }

      section h2 {
        border-bottom: 2px solid #343a40;
        padding-bottom: 10px;
        margin-bottom: 20px;
        color: #343a40;
      }

      section p {
        color: #6c757d;
      }

      html {
        scroll-behavior: smooth;
      }

      .fadeIn {
        opacity: 1;
        transform: translateY(0);
      }

      .portfolio-item:hover {
        transform: scale(1.05);
      }

      .portfolio-item img {
        border-radius: 15px;
        transition: transform 0.3s ease;
      }

      .side-headings {
        position: fixed;
        left: 20px;
        top: 50%;
        transform: translateY(-50%);
        display: flex;
        flex-direction: column;
        gap: 15px;
        z-index: 2;
      }

      .side-heading {
        color: #343a40;
        text-decoration: none;
        font-weight: bold;
        padding: 15px;
        background-color: #f8f9fa;
        border-radius: 15px;
        cursor: pointer;
        transition: background-color 0.3s ease, color 0.3s ease,
          transform 0.3s ease;
      }

      .side-heading:hover {
        background-color: #343a40;
        color: #fff;
        transform: scale(1.05);
      }

      header {
        background-attachment: fixed;
        background-position: center;
        background-repeat: no-repeat;
        background-size: cover;
        position: relative;
      }

      @keyframes bounceIn {
        0%,
        20%,
        40%,
        60%,
        80%,
        100% {
          transition-timing-function: cubic-bezier(0.215, 0.61, 0.355, 1);
          transform: translateX(0);
        }

        40% {
          transition-timing-function: cubic-bezier(0.755, 0.05, 0.855, 0.06);
          transform: translateX(-30px);
        }

        60% {
          transition-timing-function: cubic-bezier(0.755, 0.05, 0.855, 0.06);
          transform: translateX(-15px);
        }
      }

      .animated {
        animation: bounceIn 1.5s ease-out;
      }
    </style>
    <title>S A N</title>
  </head>

  <body>
    <nav>
      <a class="side-heading" href="#about">About</a>
      <a class="side-heading" href="#projects">Projects</a>
      <a class="side-heading" href="#contact">Contact</a>
    </nav>

    <header
      style="background-image: url('/static/portfolio/background.jpg')"
      class="animated"
    >
      <div class="row justify-content-center my-3">
        <div>
          <img
            class="img-fluid"
            src="/static/portfolio/santhosh_pic.PNG"
            height="300"
            width="300"
            alt="Santhosh Image"
          />
        </div>
      </div>

      <div class="row justify-content-center mb-3">
        <div class="col-md-9 text-center">
          <h1 id="hometext" class="font-weight-bold">
            Hello!😁 <br />I'm SANTHOSH <br />PATTAMUDU MANOHARAN
          </h1>
        </div>
      </div>
    </header>

    <section id="about" class="fadeIn">
      <h2>About Me</h2>
      <p>Your about me content goes here.</p>
    </section>

    <section id="projects" class="fadeIn">
      <h2>Projects</h2>
      <div class="row">
        <div class="col-lg-4 col-md-6 portfolio-item">
          <a
            href="https://github.com/santhosh1299/Password_generator_Django"
            target="_blank"
          >
            <div class="portfolio-item">
              <img
                src="/media/Portfolio/images/password.jpg"
                class="img-fluid mb-2 rounded"
                alt="Project Image"
              />
              <h3>Password Generator</h3>
              <p>
                Create a secure password using our generator tool. Help prevent
                a security threat by getting a strong password
              </p>
            </div>
          </a>
        </div>
        <!-- Add other project items similarly -->
      </div>
    </section>

    <section id="contact" class="fadeIn">
      <h2>Contact</h2>
      <!-- Add your contact form or information here -->
    </section>

    <script>
      document.querySelectorAll('a[href^="#"]').forEach((anchor) => {
        anchor.addEventListener("click", function (e) {
          e.preventDefault();
          document.querySelector(this.getAttribute("href")).scrollIntoView({
            behavior: "smooth",
          });
        });
      });

      document.addEventListener("scroll", function () {
        let sections = document.querySelectorAll("section");
        sections.forEach((section) => {
          if (window.scrollY + window.innerHeight > section.offsetTop) {
            section.classList.add("fadeIn");
          }
        });
      });
    </script>
  </body>
</html>